import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Schema } from "effect";

const PackageLock = Schema.Struct({
  packages: Schema.Struct({
    "node_modules/@xberg-io/tree-sitter-language-pack": Schema.Struct({
      version: Schema.String,
    }),
  }),
});
const SourcePackage = Schema.Struct({ version: Schema.String });
const Definitions = Schema.Record(
  Schema.String,
  Schema.Struct({ extensions: Schema.Array(Schema.String) }),
);
const decodePackageLock = Schema.decodeUnknownSync(Schema.fromJsonString(PackageLock));
const decodeSourcePackage = Schema.decodeUnknownSync(Schema.fromJsonString(SourcePackage));
const decodeDefinitions = Schema.decodeUnknownSync(Schema.fromJsonString(Definitions));

const repository = "https://github.com/xberg-io/tree-sitter-language-pack.git";
const extensionRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(extensionRoot, "../..");
const packageLock = decodePackageLock(
  readFileSync(join(workspaceRoot, "package-lock.json"), "utf8"),
);
const version = packageLock.packages["node_modules/@xberg-io/tree-sitter-language-pack"].version;

if (!/^\d+\.\d+\.\d+$/.test(version)) {
  throw new Error("Tree-sitter language pack lock must contain an exact version");
}

const temporary = mkdtempSync(join(tmpdir(), "orogeny-tree-sitter-catalog-"));
const checkout = join(temporary, "source");

try {
  execFileSync(
    "git",
    ["clone", "--quiet", "--depth", "1", "--branch", `v${version}`, repository, checkout],
    { stdio: ["ignore", "pipe", "pipe"] },
  );

  const sourcePackage = decodeSourcePackage(
    readFileSync(join(checkout, "crates/ts-pack-core-node/package.json"), "utf8"),
  );
  if (sourcePackage.version !== version) {
    throw new Error(`Source tag v${version} contains package version ${sourcePackage.version}`);
  }

  const definitions = decodeDefinitions(
    readFileSync(join(checkout, "crates/ts-pack-core/language_definitions.json"), "utf8"),
  );
  const registry = readFileSync(join(checkout, "crates/ts-pack-core/src/registry.rs"), "utf8");
  const aliasBlock = registry.match(
    /const LANGUAGE_ALIASES: &\[\(&str, &str\)\] = &\[([\s\S]*?)\n\];/,
  )?.[1];
  if (aliasBlock === undefined) {
    throw new Error("Could not find LANGUAGE_ALIASES in the language-pack registry");
  }

  const languages = new Map<string, string>();
  const add = (name: string, canonical: string) => {
    const existing = languages.get(name);
    if (existing !== undefined && existing !== canonical) {
      throw new Error(`Language tag ${name} maps to both ${existing} and ${canonical}`);
    }
    languages.set(name, canonical);
  };

  for (const name of Object.keys(definitions)) add(name, name);
  for (const [canonical, definition] of Object.entries(definitions)) {
    for (const extension of definition.extensions) add(extension, canonical);
  }
  for (const match of aliasBlock.matchAll(/\("([^"]+)",\s*"([^"]+)"\)/g)) {
    add(match[1]!, match[2]!);
  }

  const commit = execFileSync("git", ["-C", checkout, "rev-parse", "HEAD"], {
    encoding: "utf8",
  }).trim();
  const entries = [...languages].sort(([left], [right]) => left.localeCompare(right));
  const generated = `// Generated by scripts/generate-syntax-languages.ts — do not edit.\n// Source: @xberg-io/tree-sitter-language-pack ${version} (${commit})\n\nimport { HashMap } from "effect";\n\nexport const languages = HashMap.fromIterable<string, string>([\n${entries
    .map(([name, canonical]) => `  [${JSON.stringify(name)}, ${JSON.stringify(canonical)}],`)
    .join("\n")}\n]);\n`;

  writeFileSync(join(extensionRoot, "src/syntax/languages.generated.ts"), generated);
  process.stdout.write(`Generated ${entries.length} Tree-sitter language tags.\n`);
} finally {
  rmSync(temporary, { force: true, recursive: true });
}
